class SiteDataSchema:
  IMPORT_ELECTRICITY_DEMAND = 'site_import_electricity_demand', 'kWh'
  EXPORT_ELECTRICITY_DEMAND = 'site_export_electricity_demand', 'kWh'
  SELF_CONSUMED_ELECTRICITY = 'self-consumed_electricity', 'kWh'
  INIT_SITE_ELECTRICITY_DEMAND = 'initial_site_electricity_demand', 'kWh'
  ADDITIONAL_ELECTRICITY_DEMAND = 'additional_site_electricity_demand', 'kWh'
  ELECTRICITY_GENERATION = 'electricity_generation', 'kWh'
  ENERGY_INPUT = 'ENERGY_INPUT'
  INDEX = 'utc_time'


class ResultsSchema:
  INDEX = 'year'
  EXPENDITURES = 'capital_expenditures_and_maintenace', 'GBP'
  IMPORT_ELECTRICITY_PRICES = 'import_electricity_prices', 'GBP/kWh'
  TOTAL_GHG_EMISSIONS_DISPLACED = 'total_ghg_emissions_displaced', 'kgCO2e'
  SITE_GHG_EMISSIONS_DISPLACED = 'site_ghg_emissions_displaced', 'kgCO2e'
  GHG_EMISSIONS_IMPORT_ELECTRICITY = 'ghg_emissions_import_electricity', 'kgCO2e'
  GHG_INTENSITY_IMPORT_ELECTRICITY = 'ghg_intensity_import_electricity', 'kgCO2e/kWh'
  IMPORT_ELECTRICITY_COSTS = 'import_electricity_costs', 'GBP'
  EXPORT_ELECTRICITY_REVENUES = 'export_electricity_revenues', 'GBP'
  ELECTRICITY_REVENUES = 'export_electricity_revenues', 'GBP'
  ELECTRICITY_SAVINGS = 'import_electricity_savings', 'GBP'
  CAPEX = 'capital_expenditures', 'GBP'
  OPEX = 'operational_and_maintenance_expenditures', 'GBP'
  MAINTENANCE = 'maintenance_expenditures', 'GBP'
  PEAK_ELECTRICITY_IMPORT = 'peak_site_import_electricity', 'kW'
  PEAK_ELECTRICITY_EXPORT = 'peak_site_export_electricity', 'kW'
  CAPACITY_INSTALLED = 'capacity_installed', 'kW'
  PAYBACK_TIME = 'payback_time_PV_system', 'years'
  AVAILABILITY_ELECTRICITY = 'site_available_electricity_demand', 'kWh'
